name : Accompanion System Compatibility test

on:
  push:
    branches:
      - windows
      - main
  pull_request:
    branches:
      - windows
      - main

jobs:
  ubuntu_testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install System Requirements
        run: |
          sudo apt install git
          sudo apt-get install gcc
          sudo apt-get install libjack-dev
          sudo apt-get install libasound2-dev
          sudo apt install g++
          conda init bash

      - name: Setup
        run: |
          bash --login
          conda update conda
          conda env create -f environment.yml
          $CONDA/bin/activate accompanion
          pip install -e .

      - name: Run Accompanion
        run:
          ./bin/ACCompanion